### PR TITLE
Rc/v0.0.6

### LINKED ISSUE #7: Opaque error message on mod_lineplot initialization
As reported by an internal user:

> One of the [...] apps I support includes the lineplot module amongst others. When I launch the app, a non-informative error is displayed in the console:
> image
> It seems like it does not impact the app behavior. As far as I can tell, everything works fine. [...] I narrowed the source of the error down to the lineplot module, but didn’t find the time to dig deeper (☹). This happens for [...] version 0.0.3 as well as for version 0.0.4.

### LINKED ISSUE #8: Correlation heatmap fails to warn against duplicates in input dataset
The module generates an opaque error when fed data with rows with identical subject ID, category, parameter and visit values:
image

At the same time, console output (visible to the app creator but not to the app user) reads:
> Warning: Values from `value` are not uniquely identified; output will contain list-cols.
> • Use `values_fn = list` to suppress this warning.
> • Use `values_fn = {summary_fun}` to summarise duplicates.
> • Use the following dplyr code to identify duplicates.
>   {data} %>%
>   dplyr::group_by(subject_id, parameter) %>%
>   dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
>   dplyr::filter(n > 1L)

### PR DESCRIPTION
**Pull request by ml-ebs-ext**
Fixes #7. Fixes #8.

### CODE REVIEW

**Comment by ml-ebs-ext** [comment]
The lineplot bug is fixed by avoiding a `shiny::req` inside the `label_if_valid` parameter of `it_relabel_button`. That code runs inside an `observe` and that triggers the gratuitous error reported by our esteemed power user.

I think the correlation heatmap fix is easily understood looking at the `NEWS.md` file and reading the code, but contact me if you need clarification.

File: R/mod_corr_hm.R [hunk 1]
```diff
@@ -60,7 +60,11 @@ CH_MSG <- poc( # nolint
     N_SUBJECT_EMPTY_RESPONSES = function(x) {
       paste(x, "subjects with empty responses!")
     },
-    LESS_THAN_2_PARAMETER = "Please select at least 2 parameters"
+    LESS_THAN_2_PARAMETER = "Please select at least 2 parameters",
+    TOO_MANY_ROWS = paste(
+      "The dataset provided contains repeat rows with identical subject, category, parameter and",
```
Comment (mattkorb) [inline R/mod_corr_hm.R:65]:
```suggestion
      "The dataset provided contains repeated rows with identical subject, category, parameter and",
```

**Review by mattkorb — DISMISSED** [review]
@ml-ebs-ext One small suggestion, but besides that it looks good.

**Review by mattkorb — APPROVED** [review]
